import type { Metadata } from "next";
import "./globals.scss";
import {gilroy} from "@/utils/fonts/customFonts";

export const metadata: Metadata = {
  title: "KS Tech",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={gilroy.className}>{children}</body>
    </html>
  );
}
